#!/usr/bin/env node
/**
 * obsidianTheme asset builder.
 * Concatenates the Obsidian CSS token/component/layout files into the
 * single-file bundles referenced by conf.yml (admin.css / dashboard.css).
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const CSS_DIR = path.join(ROOT, 'resources', 'css', 'obsidianTheme');
const OUT_DIR = path.join(ROOT, 'assets');
const ORDER = [
  'obsidian-base.css',
  'obsidian-tokens.css',
  'obsidian-animations.css',
  'obsidian-components.css',
  'obsidian-layouts.css',
];

for (const f of ORDER) {
  if (!fs.existsSync(path.join(CSS_DIR, f))) {
    console.error(`FATAL: missing CSS source file: resources/css/obsidianTheme/${f}`);
    process.exit(1);
  }
}

const banner = (name) =>
  `/*! obsidianTheme ${name} - generated by scripts/build-assets.js. Do not edit by hand. */\n\n`;

const bundle = ORDER.map((f) => `/* ==== ${f} ==== */\n` + fs.readFileSync(path.join(CSS_DIR, f), 'utf8')).join('\n');

fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(path.join(OUT_DIR, 'admin.css'), banner('admin.css') + bundle);
fs.writeFileSync(path.join(OUT_DIR, 'dashboard.css'), banner('dashboard.css') + bundle);
// Webpack-imported copy (see components/ObsidianBootstrap.tsx) — bypasses the
// fragile trailing @import in Blueprint's extensions.css entirely.
fs.writeFileSync(path.join(ROOT, 'components', 'theme.css'), banner('theme.css') + bundle);
console.log('Built assets/admin.css and assets/dashboard.css');